settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: provisioner
  path: .
  commands: 
    fmt:
      status: true
    install:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
    - web
